config/routes.rb
Ratemypup::Application.routes.draw do
  root :to => 'pups#main'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  match '/pups/create' => 'pups#create', :as => :create_pup
  post 'breeders' => 'breeders#create', :as => :create_breeder
  get 'pups/dog_name' => 'pups#dog_name', :as => :dog_name
  get 'pups/dog_how_long' => 'pups#dog_how_long', :as => :dog_how_long
  get 'pups/dog_breed' => 'pups#dog_breed', :as => :dog_breed
  get 'pups/dog_breeder' => 'pups#dog_breeder', :as => :dog_breeder

  resources :pups
  resources :breeders
  resources :texts

  get '/breed' => 'pups#breed', :as => :breed
  get '/breed/match' => 'pups#search_breed', :as => :breed_search
  get '/breeder/search_name' => 'breeders#search_name', :as => :breeder_search
  get '/breeder/match' => 'breeders#search_breeder', :as => :breeder_substring_match
  
  get '/text/mission' => 'texts#mission', :as => :text_mission
  get '/text/background' => 'texts#background', :as => :text_background
  get '/text/goals' => 'texts#goals', :as => :text_goals
  get '/text/how_you_can_help' => 'texts#how_you_can_help', :as => :text_how_you_can_help
  get '/welcome' => 'texts#welcome', :as => :welcome
  

end

app/models/pup.rb
class Pup < ActiveRecord::Base

  belongs_to :user
  belongs_to :breeder
  belongs_to :breed

  has_one :comment, dependent: :destroy

  validates :pup_name, :presence => true
  validates :user_id, :presence => true
  validates :breeder_id, :presence => true
  validates :breed_id, :presence => true
  validates :breeder_responsibility, :presence => true
  validates :overall_health, :presence => true
  validates :trainability, :presence => true
  validates :social_behavior, :presence => true
  validates :energy_level, :presence => true
  validates :simpatico_rating, :presence => true

  attr_accessible :pup_name, :year, :month, :user_id, :breeder_id, :breed_id, :breeder_responsibility, :overall_health,
                  :trainability, :social_behavior,:dog_behavior, :energy_level, :simpatico_rating, :kennel,
                  :hashtag_1, :hashtag_2, :hashtag_3


  before_destroy { |pup| pup.breeder ? pup.breeder.increment_deleted_reviews : nil }



  # assets

  def safe_hashtag_string
    [hashtag_1, hashtag_2, hashtag_3].select{|hashtag| hashtag}
  end



  # class methods
  def Pup.find_by_breed(breed_name)
    breed_id = Breed.where("name = ?", breed_name)
    Pup.where("breed_id = ?", breed_id).order("created_at DESC")
  end

  def Pup.avg_ratings_by_breed(breed_name)
    pups_by_breed = Pup.find_by_breed(breed_name)
    results_hash = {:overall_health => 0, :trainability => 0, :social_behavior => 0,
                    :dog_behavior => 0, :energy_level => 0, :simpatico_rating => 0}
    results_num = {:overall_health => 0, :trainability => 0, :social_behavior => 0,
                   :dog_behavior => 0, :energy_level => 0, :simpatico_rating => 0}
    pups_by_breed.each do |pup|
      results_hash.each do |rating, value|
        unless pup.send(rating) == 0
          results_hash[rating] += pup.send(rating)
          results_num[rating] += 1
        end
      end
    end
    results_hash.each do |k,v|
      results_hash[k] = 1.0 * results_hash[k]/results_num[k] if results_num[k] > 0
    end
    results_hash
  end




end

app/controllers/pups_controller.rb
class PupsController < ApplicationController

  before_filter :breeder_exists, :only => :create
  before_filter :check_sign_in, :only => [:new, :dog_name, :dog_how_long, :dog_breed, :dog_breeder]

  # Devise. Methods not in the list below will require a user to be logged in.
  before_filter :authenticate_user!, except: [:index, :new, :main, :show, :breed, :search_breed]


  def breeder_exists
    if params[:pup][:breeder_id].to_i == -1
      breeder = Breeder.find_or_create(params[:breeder][:name], params[:breeder][:city], params[:breeder][:state])
      params[:pup][:breeder_id] = breeder.id
    end
  end



  # The Root Path
  def main
    start_over
    selected_comment = SelectedComment.find_randomly
    if selected_comment
      @comment_content = selected_comment.content
      @comment_user = selected_comment.user
    end
  end



  # The true rating page
  def new
    if !session[:step1] || !session[:step2] || !session[:step3]
      redirect_to root_path and return
    end
    if !session[:breeder_id]
      breeder_str = params[:breeder][:name]
      if breeder_str.empty?
        session[:breeder_id] = 1
        return
      end
      breeder = Breeder.find_by_formatted_string(breeder_str)
      if breeder
        session[:breeder_id] = breeder.id
        return
      end
      flash[:notice] = "The dog breeder or kennel you entered is not yet in our database.
      Please click here to add it to our database."
      redirect_to dog_breeder_path and return
    end
  end



  # Rails default methods
  def index
    @pups = Pup.all
  end


  def show
    @pup = Pup.find params[:id]
  end

  def create
    # gather pup ifo
    new_pup = {}
    new_pup[:pup_name] = session[:pup_name]
    new_pup[:year] = session[:years] || 0
    new_pup[:month] = session[:months] || 0
    new_pup[:breeder_responsibility] = params[:pup][:breeder_responsibility]
    new_pup[:overall_health] = params[:pup][:overall_health]
    new_pup[:trainability] = params[:pup][:trainability]
    new_pup[:social_behavior] = params[:pup][:social_behavior]
    new_pup[:dog_behavior] = params[:pup][:dog_behavior]
    new_pup[:energy_level] = params[:pup][:energy_level]
    new_pup[:simpatico_rating] = params[:pup][:simpatico_rating]
    new_pup[:hashtag_1] = params[:pup][:hashtag_1]
    new_pup[:hashtag_2] = params[:pup][:hashtag_2]
    new_pup[:hashtag_3] = params[:pup][:hashtag_3]
    new_pup[:breed_id] = Breed.find_by_name(session[:breed]).id
    new_pup[:breeder_id] = session[:breeder_id]
    new_pup[:user_id] = current_user.id
    @pup = Pup.new(new_pup)
    new_comment = {:content => params[:pup][:comments]}
    @Comment = Comment.new(new_comment)

    if !@pup.valid?
      flash[:notice] = 'Please make sure all fields are complete!'
      redirect_to new_pup_path and return
    end
    if !@Comment.valid?
        flash[:notice] = 'Please make sure the comment is less than 140 characters.'
        redirect_to new_pup_path and return
    end

    @pup.save
    @Comment.pup_id = @pup.id
    @Comment.save

    # Successfully save pup & comment
    flash[:notice] = "Thank You! #{@pup.pup_name} was successfully added to our database."
    redirect_to root_path
  end

  def update
    @pup = Pup.find params[:id]
    @pup.update_attributes(params[:pup])
    redirect_to pups_path
  end

  def destroy
    @pup = Pup.find params[:id]
    @pup.destroy
    redirect_to pups_path
  end



  #################### Start Questionnaire ####################

  # step 0
  def dog_name
  end

  # step 1
  def dog_how_long
    if params[:pup]
      pup_name = params[:pup][:name]
    else
      pup_name = session[:pup_name]
    end
    if pup_name.nil? || pup_name.empty?
      flash[:notice] = "Please input a name"
      session[:step1] = false
      redirect_to dog_name_path and return
    else
      session[:pup_name] = pup_name
      session[:step1] = true
    end
  end

  #step2
  def dog_breed
    if !session[:step1]
      redirect_to root_path and return
    end
    if params[:pup]
      years = params[:pup][:years]
      months = params[:pup][:months]
    else
      years = session[:years]
      months = session[:months]
    end
    # tmp_session = {:name => session[:pup_name]}
    if years.nil? || months.nil? || (years.empty? && months.empty?)
      flash[:notice] = "Please enter how long you have owned your dog."
    elsif (!years.empty? && !is_num?(years)) || (!months.empty? && !is_num?(months))
      flash[:notice] = "Please enter a valid integer number for year/month."
    elsif is_valid_year_month?(years, months)
      session[:years] = years
      session[:months] = months
      session[:step2] = true
      return
    else
      flash[:modal] = "modal"
    end
    session[:step2] = false
    redirect_to dog_how_long_path
  end

  #step3
  def dog_breeder
    if !session[:step1] || !session[:step2]
      redirect_to root_path and return
    end
    if params[:breed]
      breed = params[:breed][:name]
    else
      breed = session[:breed]
    end
    if !Breed.is_valid_breed breed
      session[:step3] = false
      flash[:modal] = "modal"
      temp_session = {:years => session[:years], :months => session[:months]}
      redirect_to dog_breed_path and return
    end
    session[:breed] = breed
    session[:step3] = true

  end

  #################### End Questionnaire ####################



  # search for breeds when doing auto-fill
  def search_breed
    name = params[:name]
    render :json => Breed.find_breed_by_substr(name)
  end

  # search pups by breed name
  def breed
    name = params[:breed][:name]
    if !Breed.is_valid_breed(name)
      flash[:notice] = "Please enter a vild breed name."
      redirect_to root_path
    end
    @pups = Pup.find_by_breed(name)
    @avg_ratings = Pup.avg_ratings_by_breed(name)
  end



  private
  def check_sign_in
    unless user_signed_in?
      redirect_to welcome_path
    end
  end
  
  def is_valid_year_month?(years, months)
    return years.to_i * 12 + months.to_i >= 6
  end

  def is_num?(str)
    Integer(str)
    return true
  rescue ArgumentError, TypeError
    return false
  end

  def start_over
    session[:step1] = false
    session[:step2] = false
    session[:step3] = false
    session[:pup_name] = nil
    session[:breed] = nil
    session[:years] = nil
    session[:months] = nil
    session[:breeder_id] = nil
  end
end
  

app/views/pups/_accordion.html.haml
%div{:class => "panel panel-default"}
  %div{:class => "panel-heading", :role => "tab", :id => "heading" + num}
    %h4{:class => "panel-title"}
      %a{"data-toggle" => "collapse", "data-parent" => "#accordion", :href => "#collapse" + num, "aria-expanded" => "true", "aria-controls" => "collapse" + num}
        = title
  %div{:id => "collapse" + num, :class => "panel-collapse collapse " + open, "data-parent" => "#accordion", :role => "tabpanel", "aria-labelledby" => "heading" + num}
    %div{:class => "panel-body"}
      = text

app/views/pups/_breed_checkbox.html.haml
%div{:class => "form-group great row"}
	%div{:class => "radio-text"}
	%div{:id => "primary-breed"}
		= render 'select_input', title: "Primary Breed", list: @all_breeds, var: :breed_1

app/views/pups/_dog_breeder_popup.html.haml
%div{:class=>"modal fade", :id=>"popup", :tabindex=>"-1", :role=>"dialog"}
  %div{:class=>"modal-dialog", :role=>"document"}
    %div{:class=>"modal-content"}
      %div{:class=>"modal-header"}
        %div{:class=>"modal-title"}
          %h3{:align=>"center" }
            = info[:header]
        %div{:class=>"modal-body"}
          %p
            = info[:content]
        %div{:class=>"modal-footer"}
        %button{:class=>"btn btn-default", :data=>{:dismiss=>"modal"}} Close

app/views/pups/_popup.html.haml
%div{:class=>"modal fade", :id=>"popup", :tabindex=>"-1", :role=>"dialog"}
  %div{:class=>"modal-dialog", :role=>"document"}
    %div{:class=>"modal-content"}
      %div{:class=>"modal-header"}
        %div{:class=>"modal-title"}
          %h3{:align=>"center" }
            = info[:header]
        %div{:class=>"modal-body"}
          %p
            = info[:content]
        %div{:class=>"modal-footer"}
          -if info[:close]
            %button{:class=>"btn btn-default", :data=>{:dismiss=>"modal"}} Close
          =link_to "Go Back to Homepage", root_path, :class=>"btn btn-primary"

app/views/pups/_slider_rating.html.haml
.price-slider.row
    .col-sm-10
        .row
            .col-sm-5
                %h4{:class => "great"}=label :pup, var, title
                %br
                %span #{description}
            .col-sm-2
                %br
                %br
                %br
                %h5 #{des1}
            .col-sm-3
                %br
                %br
                %br
                %div{:class => "paw"}
                    %div{:class => "pull-left"}
                        %i{:class =>"fa fa-paw fa-2x", :id => "#{id}-first"}
                    %div{:class => "pull-left"}
                        %i{:class =>"fa fa-paw fa-2x", :id => "#{id}-second"}
                    %div{:class => "pull-left"}
                        %i{:class => "fa fa-paw fa-2x", :id => "#{id}-third"}
                    %div{:class => "pull-left"}
                        %i{:class =>"fa fa-paw fa-2x", :id => "#{id}-fourth"}
                    %div{:class => "pull-left"}
                        %i{:class => "fa fa-paw fa-2x", :id => "#{id}-fifth"}
                    %div{:class=>"text-left"}
                        = text_field :pup, var, :class => "read", :id => id, :value => "0", :readonly => true
            .col-sm-2
                %br
                %br
                %br
                %h5 #{des5}

    .col-sm-2
        .row
            %br
            %br
            %br
            .pull-left.paw
                .col-sm-8
                .col-sm-4
                    %i{:class => "fa fa-paw fa-2x", :id => "#{id}-sixth"}

        %br
        &nbsp;&nbsp;&nbsp;&nbsp;Unknown
                        

app/views/pups/_tags_input.html.haml
%div{:class=>"tag-holder hidden", :id=>"chooseTagModal"}
    %a{:href=>"#", :class=>"hashtag"} Easy to obedience train
    %a{:href=>"#", :class=>"hashtag"} Hard to obedience train
    %a{:href=>"#", :class=>"hashtag"} Easy to housetrain
    %a{:href=>"#", :class=>"hashtag"} Hard to housetrain
    %a{:href=>"#", :class=>"hashtag"} High energy
    %a{:href=>"#", :class=>"hashtag"} Calm personality
    %a{:href=>"#", :class=>"hashtag"} Barks a lot
    %a{:href=>"#", :class=>"hashtag"} Very quiet
    %a{:href=>"#", :class=>"hashtag"} One person dog
    %a{:href=>"#", :class=>"hashtag"} Friendly toward everyone
    %a{:href=>"#", :class=>"hashtag"} Unpredictable with strangers
    %a{:href=>"#", :class=>"hashtag"} Unpredictable with children
    %a{:href=>"#", :class=>"hashtag"} Independent
/ %a{:href=>"#", :class=>""}
/ Constant companion around home
/ %a{:href=>"#", :class=>""}
/ Great with other dogs
/ %a{:href=>"#", :class=>""}
/ Unpredictable with other dogs
/ %a{:href=>"#", :class=>""}
/ Great with cats, other small animals
/ %a{:href=>"#", :class=>""}
/ Unpredictable with cats, other small animals
/ %a{:href=>"#", :class=>""}
/ Loves to play ball, fetch
/ %a{:href=>"#", :class=>""}
/ Well mannered, can go anywhere with me
/ %a{:href=>"#", :class=>""}
/ Eats poop or other disgusting things
/ %a{:href=>"#", :class=>""}
/ Sheds a lot
/ %a{:href=>"#", :class=>""}
/ Coat needs frequent grooming

app/views/pups/_text_input.html.haml
/ = label :pup, :pup_name, title
/ = text_field :pup, var, :class => "form-control", :placeholder => placeholder
= label :pup, var, title
%div{:class => "explanation"} #{explanation}
= text_field :pup, var, :class => "form-control", :placeholder => placeholder

app/views/pups/breed.html.haml
=render "shared/results", query: "#{params[:breed][:name]}"

app/views/pups/dog_breed.html.haml
%div{:class => "container"}
  %div{:class => "header"}
    %h1 Rate Your Dog

  = form_tag dog_breeder_path, :class => "form-horizontal", :autocomplete => "off", :method=>'get' do

    /BASIC INFO GROUP/
    %div{:class => "sub-header"}
      %h3 Please indicate your dog's breed.
    %br
      
   
    // = render 'breed_checkbox'
    %div{:class => "form-group great text-center", :class => "sub-title"}
      = text_field :breed, :name, :class => "form-control", :id => "breed_find", :placeholder => "Breed Name"
      %div{:id => 'breed_autofills', :class => "form-group col-md-12"}
    
    %br
    %br
    %div{:class => "form-group col-sm-5"}
      = submit_tag 'Next', :class => "form-control", :id => 'next_button'
    %div{:class => "form-group col-sm-2"}
    -#%div{:class => "form-group col-sm-5"}
    -#  = submit_tag 'Breed Not Listed', :name => "button_clicked", :class => "form-control", :id => 'back_button'

= render 'popup', :info => {:header => "Please select a breed in the list.", :close => "", :content => "We are only collecting information for dogs that are purebred members of an American Kennel Club (AKC) breed, or are among the most popular hybrid crosses of two AKC breeds. If your dog is of unknown ancestry or is a breed or cross that is not listed in our database, we appreciate your willingness to contribute information about your dog but do not have a meaningful way of organizing data for your dog at this time."}
- if flash[:modal]
  :javascript
    $(document).ready(function() {
      $('#popup').modal({backdrop:'static', keyboard:false});
    })

app/views/pups/dog_breeder.html.haml
%div{:class => "container"}
  %div{:class => "header"}
    %h1 Rate Your Dog


    /BASIC INFO GROUP/
    %div{:class => "sub-header"}
      %h3 Please indicate your dog's breeder. (Optional)
    %br

  = form_tag new_pup_path, :class => "form-horizontal", :autocomplete => "off", :method=>'get' do
    %div{:class => "form-group", :class => "sub-title"}
      = label :pup, "Breeder/Kennel Information"
      %div{:class => "explanation", :style => "font-size: 16px;"}
        Type the name of the dog breeder or kennel from which you acquired your dog below,
        and then click on the correct breeder/kennel from the drop down list.
        If the name does not appear, please add the name of the dog breeder, city and state
        to our database by clicking
        %strong
          = link_to  %"here", new_breeder_path
        \. If you do not know the name, city and state of your dog's breeder, simply click "Next".

      %div{:class => 'collapse in', :id => 'breeder_form_collapse'}
        = text_field :breeder, :name, :class => "form-control", :id => "breeder_form", :placeholder => "Breeder Name"
        = text_field :breeder, :new, :class => "form-control", :id =>"invisible_field", :type => 'hidden'
        %div{:id => 'autofills', :class => "form-group col-md-12"}
    %br
    %br
    %div{:class => "form-group col-sm-5"}
      = submit_tag 'Next', :class => "form-control", :id => 'next_button'

app/views/pups/dog_how_long.html.haml
%div{:class => "container"}
  %div{:class => "header"}
    %h1 Rate Your Dog

  = form_tag dog_breed_path, :class => "form-horizontal", :autocomplete => "off", :method => 'get' do

    /BASIC INFO GROUP/
    %div{:class => "sub-header"}
      %h3 How long have you owned your dog?
    %br
    %div{:class => "form-group great text-center", :class => "sub-title"}
      = render 'text_input', title: "Years", var: 'years', placeholder: "Years", explanation: "Enter the number of years you have owned your dog."
      %br
      = render 'text_input', title: "Months", var: 'months', placeholder: "Months", explanation: "And/or enter the number of months you have owned your dog."

    %br
    %br

    %div{:class => "form-group col-sm-5"}
      = submit_tag 'Next', :id => 'next_button', :class => "form-control", :confirm => ""

= render 'popup', :info => {:header=>"We are sorry", :content=>"To keep our database as accurate as possible, we are collecting information only for dogs that have been residing in their current home for six months or more. Please come back to our site and rate your dog after s/he has lived with you for a minimum of six months. Thank you."}

- if flash[:modal]
  :javascript
    $(document).ready(function() {
      $('#popup').modal({backdrop:'static', keyboard:false});
    })

app/views/pups/dog_name.html.haml
%div{:class => "container"}
  %div{:class => "header"}
    %h1 Rate Your Dog

  = form_tag dog_how_long_path, :class => "form-horizontal", :autocomplete => "off", :method => 'get' do

    /BASIC INFO GROUP/
    %div{:class => "sub-header"}
      %h3 Let's get some basic information about your dog!
    %br
    %div{:class => "form-group great text-center", :class => "sub-title"}
      = render 'text_input', title: "What's your dog's name?", var: 'name', placeholder: "Name", explanation: "Name is for our records only, your pup's name will never show up on public ratings pages."
      %br

    %div{:class => "form-group col-sm-5"}
      = submit_tag 'Next', :class => "form-control", :id => 'next_button'

app/views/pups/new.html.haml
/ %body{:style => "background-color:#EBFAFF"}

%div{:class => "container"}

  %div{:class => "header"}
    %h1 Rate Your Dog

  %br
  
  / http://bootsnipp.com/user/snippets/0M39d
  = form_tag pups_path, :class => "form-horizontal", :autocomplete => 'off' do

    /ATTRIBUTES GROUP/
    %div{:class => "sub-header"}
      %h3 How would you rate your pup?
    %h4{:class => "explanation"}
      (1 = Poor, 5 = Excellent)
    = render 'slider_rating', title: "Breeder Responsibility", slider: "slider-breeder", id: "breeder-label",
              des1: "Poor Breeder Responsibility", des5: "Excellent Breeder Responsibility",
              description: "Responsible dog breeders screen their breeder dogs for breed-related genetic problems, begin early training and socialization of the puppies they produce, provide a health guarantee and ongoing support for the puppies they sell, and provide excellent lifelong health care and quality of life for their breeding dogs. Please rate the breeder of your dog for the level of responsibility they demonstrated.", var: :breeder_responsibility
    = render 'slider_rating', title: "Overall Health", slider: "slider-health", id: "health-label",
              des1: "Poor Health", des5: "Excellent Health",
              description: "Please rate your dog's overall health in the time that you have had him/her. Please do not consider health problems that were the result of accidental injuries.", var: :overall_health
    = render 'slider_rating', title: "Trainability", slider: "slider-train", id: "train-label",
              des1: "Difficult to Train", des5: "Easy to Train",
              description: "Please rate how easy your dog has been to train: consider housetraining, obedience training, and basic manners.", var: :trainability
    = render 'slider_rating', title: "Social Behavior Toward Humans", slider: "slider-social", id: "social-label",
              des1: "Very Unfriendly Toward Humans", des5: "Always Very Friendly Toward Everyone",
              description: "Please rate your dog's social response to others, including family members, strangers, adults and children.", var: :social_behavior
    = render 'slider_rating', title: "Behavior Toward Other Dogs", slider: "slider-behavior", id: "behavior-label",
              des1: "Very Unfriendly Toward Other Dogs", des5: "Always Very Friendly Toward Other Dogs",
              description: "Please rate your dog's overall reaction toward other dogs, both familiar and unfamiliar.", var: :dog_behavior
    = render 'slider_rating', title: "Energy Level", slider: "slider-energy", id: "energy-label",
              des1: "Low Energy Level", des5: "High Energy Level, needs lots of exercise",
              description: "Please rate your dog's overall energy level and exercise requirement at maturity (1--7 years of age).", var: :energy_level
    = render 'slider_rating', title: "Simpatico Rating", slider: "slider-simpatico", id: "simpatico-label",
              des1: "Low Simpatico rating: Hard to connect with this dog", des5: "High Simpatico rating: Most compatible dog I've ever had",
              description: "Some dogs just seem to have what it takes to be the ultimate companion. Please give your dog an overall Simpatico rating, based on the overall compatibility that your dog has and the depth of the relationship you share.", var: :simpatico_rating
    
    %div{:class => "row"}
      = render 'tags_input'

    /HASHTAGS GROUPING/
    %div{:class => "form-group col-lg-12", :id => "hashtags"}
      %h3 Choose up to three of the following:
      = text_field :pup, 'hashtag_1', :class => "form-control", :id =>"invisible_hashtag_1", :type => 'hidden'
      = text_field :pup, 'hashtag_2', :class => "form-control", :id =>"invisible_hashtag_2", :type => 'hidden'
      = text_field :pup, 'hashtag_3', :class => "form-control", :id =>"invisible_hashtag_3", :type => 'hidden'

    /COMMENTS GROUPING/
    %div{:class => "sub-header"}
      %h3 Tell us more!
    %h4{:class => "explanation"} What do you feel are the most important positive or negative aspects of your dog? (140 chars limit)
    %br
    %div{:class => "form-group col-sm-12"}
      = text_field :pup, 'comments', :class => "form-control", :placeholder => "Comments"
    
    %br

    %div{:class => "form-group col-sm-5"}
      = submit_tag 'Submit information about this dog', :id => 'Add Pup', :class => "form-control"
    %script{:src=>"https://code.jquery.com/ui/1.10.4/jquery-ui.min.js"}
    

app/views/pups/show.html.haml
%div{:class => "container"}

  %table#pup{:class => "table"}
    %thead
      %tr
        %th Puppy Name
        %th Owner Name
        / %th Breeder
        %th Breed 1
        %th Breed 2
        %th Breeder Responsibility
        %th Overall Health
        %th Trainability
        %th Social Behavior
        %th Energy Level
        %th Simpatico Rating
        %th Comments
        %th More

    %tbody
      %tr
        %td= @pup.pup_name
        %td= @pup.owner_name
        / %td= @pup.breeder
        %td= @pup.breed_1
        %td= @pup.breed_2
        %td= @pup.breeder_responsibility
        %td= @pup.overall_health
        %td= @pup.trainability
        %td= @pup.social_behavior
        %td= @pup.energy_level
        %td= @pup.simpatico_rating
        %td= @pup.comments


  = button_to 'Delete pup', pup_path(:id => @pup.id), :method => :delete
  %br
  = button_to 'All pups', pups_path, :method => :get