config/routes.rb
Ratemypup::Application.routes.draw do
  root :to => 'pups#main'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  match '/pups/create' => 'pups#create', :as => :create_pup
  post 'breeders' => 'breeders#create', :as => :create_breeder
  get 'pups/dog_name' => 'pups#dog_name', :as => :dog_name
  get 'pups/dog_how_long' => 'pups#dog_how_long', :as => :dog_how_long
  get 'pups/dog_breed' => 'pups#dog_breed', :as => :dog_breed
  get 'pups/dog_breeder' => 'pups#dog_breeder', :as => :dog_breeder

  resources :pups
  resources :breeders
  resources :texts

  get '/breed' => 'pups#breed', :as => :breed
  get '/breed/match' => 'pups#search_breed', :as => :breed_search
  get '/breeder/search_name' => 'breeders#search_name', :as => :breeder_search
  get '/breeder/match' => 'breeders#search_breeder', :as => :breeder_substring_match
  
  get '/text/mission' => 'texts#mission', :as => :text_mission
  get '/text/background' => 'texts#background', :as => :text_background
  get '/text/goals' => 'texts#goals', :as => :text_goals
  get '/text/how_you_can_help' => 'texts#how_you_can_help', :as => :text_how_you_can_help
  get '/welcome' => 'texts#welcome', :as => :welcome
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<!--Devise flash notices-->

<head>
  <link rel="icon" href="/assets/icon.png">
  <title>SimpaticoPup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Devise user login buttons -->
  <div class="container-fluid" style="padding-top:50px">
    <nav class="navbar navbar-default navbar-fixed-top custom-navbar">
      <div class="container-fluid">
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li>
                <div class="navbar-header">
                  <a class="navbar-brand" href="/" style="font-size: 24px; padding-left:50px;">SimpaticoPup</a>
                </div>
              </li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
              <li> 
                <%= link_to @mission, text_mission_path %>
              </li>
              <li> 
                <%= link_to @background, text_background_path %>
              </li>
              <li> 
                <%= link_to @goals, text_goals_path %>
              </li>
              <li> 
                <%= link_to @how_you_can_help, text_how_you_can_help_path %>
              </li>
              <li> 
                <%= link_to "Community Forum", root_path %>
              </li>
              
              <% if user_signed_in? %>

                  <li>
                    <span class="navbar-text"><%= "Logged in as " + current_user.username %></span>
                  </li>

                  <li>
                    <%= link_to "Edit Profile", edit_user_registration_path %>
                  </li>

                  <li>
                    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                  </li>
              <% else %>
                  <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Signup", new_user_registration_path %></button></li>
                  <li><%= link_to "Login", new_user_session_path, :id => 'Login' %></li>
              <% end %>
            </ul>
          </div>
      </div>
    </nav>

    <% flash.each do |type, message| %>
      <% if type != :modal %>
        <div class="alert <%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>